INSERT INTO INVENTORY_CATEGORY VALUES(01, 'men');
INSERT INTO INVENTORY_CATEGORY VALUES(02, 'women');
INSERT INTO INVENTORY_CATEGORY VALUES(03, 'accessories');
INSERT INTO INVENTORY_CATEGORY VALUES(04, 'sale');

INSERT INTO INVENTORY_TYPE VALUES(01, 'shirt');
INSERT INTO INVENTORY_TYPE VALUES(02, 'pants');
INSERT INTO INVENTORY_TYPE VALUES(03, 'dress');
INSERT INTO INVENTORY_TYPE VALUES(04, 'shoes');
INSERT INTO INVENTORY_TYPE VALUES(05, 'belt');
INSERT INTO INVENTORY_TYPE VALUES(06, 'jewelry');

INSERT INTO INVENTORY_ITEMS VALUES(01, 'small', 'shirt', '', 'women', 15, 25.00, 'Womens Test shirt');
INSERT INTO INVENTORY_ITEMS VALUES(02, 'small', 'shirt', '', 'men', 15, 25.00, 'Mens test shirt');
INSERT INTO INVENTORY_ITEMS VALUES(03, '12', 'shoes', '', 'accessory', 15, 25.00, 'Test Accessory');
INSERT INTO INVENTORY_ITEMS VALUES(04, 'small', 'shirt', '', 'sale', 15, 25.00, 'Sale test shirt');