CREATE DATABASE IF NOT EXISTS GUCCl;

CREATE TABLE IF NOT EXISTS account (
  accountID Integer  AUTO_INCREMENT NOT NULL,
  firstName VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(20) NOT NULL,
  subscribe BIT(0),

  PRIMARY KEY (accountID)

);
